"""First-boot provisioning (architecture §10).

Flow on the appliance image: no known WiFi → bring up a ``MeshRadio-Setup``
AP via NetworkManager (nmcli) → captive portal (a minimal FastAPI page)
collects WiFi credentials, the #music channel key, hardware profile, and
optionally the CoreScope URL → write /etc/meshradio/config.toml → reboot
into the service.

This module is invoked by a separate systemd unit (meshradio-provision) that
only runs when no connection comes up — it is NOT part of the main app
process. Implementation lands with the pi-gen image work; the config-writing
helper below is shared with the web settings page, so it lives here now.
"""

from __future__ import annotations

import json
from pathlib import Path


def _quote(value: str) -> str:
    """TOML basic string with escaping (json.dumps output is TOML-valid).
    A quote or backslash in a channel key must not brick first boot."""
    return json.dumps(str(value))


def write_config_toml(
    path: str | Path,
    *,
    hardware_profile: str,
    channel_key: str = "",
    corescope_url: str = "",
) -> None:
    """Render a minimal config.toml for a freshly provisioned radio."""
    content = f"""# Generated by MeshRadio first-boot setup
hardware_profile = {_quote(hardware_profile)}
data_dir = "/var/lib/meshradio"

[mesh]
enabled = {"true" if hardware_profile == "pi4" else "false"}
channel_key = {_quote(channel_key)}

[corescope]
enabled = true
base_url = {_quote(corescope_url)}
"""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
